build_from:
  aarch64: ghcr.io/hassio-addons/base:18.2.0
  amd64: ghcr.io/hassio-addons/base:18.2.0
  armhf: ghcr.io/hassio-addons/base:18.2.0
  armv7: ghcr.io/hassio-addons/base:18.2.0
  i386: ghcr.io/hassio-addons/base:18.2.0
args:
  DOCKGE_VERSION: 1.5.0
