name: "Dockge"
description: "A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager"
version: "1.5.0"
slug: "dockge"
init: false
ingress: true
ingress_port: 5001
ingress_stream: true
panel_icon: mdi:docker
panel_title: Dockge
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
watchdog: tcp://[HOST]:[PORT:5001]/
ports:
  5001/tcp: 5001
ports_description:
  5001/tcp: "Web interface"
host_network: false
apparmor: true
hassio_api: true
docker_api: true
hassio_role: admin
map:
  - ssl:ro
  - data:rw
  - media:rw
  - share:rw
options:
  log_level: info
  stacks_dir: /opt/stacks
  hide_hassio_containers: true
schema:
  log_level: list(trace|debug|info|warning|error|fatal)?
  stacks_dir: str?
  hide_hassio_containers: bool?